/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpazilasRouteImport } from './routes/upazilas'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpazilaSlugRouteImport } from './routes/upazila.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminUpazilaInfoRouteImport } from './routes/_authenticated/admin.upazila-info'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin.notices'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminCommitteeRouteImport } from './routes/_authenticated/admin.committee'
import { Route as AuthenticatedAdminAlumniRouteImport } from './routes/_authenticated/admin.alumni'

const UpazilasRoute = UpazilasRouteImport.update({
  id: '/upazilas',
  path: '/upazilas',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpazilaSlugRoute = UpazilaSlugRouteImport.update({
  id: '/upazila/$slug',
  path: '/upazila/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUpazilaInfoRoute =
  AuthenticatedAdminUpazilaInfoRouteImport.update({
    id: '/admin/upazila-info',
    path: '/admin/upazila-info',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/admin/notices',
    path: '/admin/notices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/admin/gallery',
    path: '/admin/gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/admin/events',
    path: '/admin/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCommitteeRoute =
  AuthenticatedAdminCommitteeRouteImport.update({
    id: '/admin/committee',
    path: '/admin/committee',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAlumniRoute =
  AuthenticatedAdminAlumniRouteImport.update({
    id: '/admin/alumni',
    path: '/admin/alumni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/auth': typeof AuthRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/notices': typeof NoticesRoute
  '/teachers': typeof TeachersRoute
  '/upazilas': typeof UpazilasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/upazila/$slug': typeof UpazilaSlugRoute
  '/admin/alumni': typeof AuthenticatedAdminAlumniRoute
  '/admin/committee': typeof AuthenticatedAdminCommitteeRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/upazila-info': typeof AuthenticatedAdminUpazilaInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/auth': typeof AuthRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/notices': typeof NoticesRoute
  '/teachers': typeof TeachersRoute
  '/upazilas': typeof UpazilasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/upazila/$slug': typeof UpazilaSlugRoute
  '/admin/alumni': typeof AuthenticatedAdminAlumniRoute
  '/admin/committee': typeof AuthenticatedAdminCommitteeRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/upazila-info': typeof AuthenticatedAdminUpazilaInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alumni': typeof AlumniRoute
  '/auth': typeof AuthRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/notices': typeof NoticesRoute
  '/teachers': typeof TeachersRoute
  '/upazilas': typeof UpazilasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/upazila/$slug': typeof UpazilaSlugRoute
  '/_authenticated/admin/alumni': typeof AuthenticatedAdminAlumniRoute
  '/_authenticated/admin/committee': typeof AuthenticatedAdminCommitteeRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/upazila-info': typeof AuthenticatedAdminUpazilaInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumni'
    | '/auth'
    | '/committee'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/members'
    | '/notices'
    | '/teachers'
    | '/upazilas'
    | '/dashboard'
    | '/profile'
    | '/upazila/$slug'
    | '/admin/alumni'
    | '/admin/committee'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/members'
    | '/admin/notices'
    | '/admin/upazila-info'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumni'
    | '/auth'
    | '/committee'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/members'
    | '/notices'
    | '/teachers'
    | '/upazilas'
    | '/dashboard'
    | '/profile'
    | '/upazila/$slug'
    | '/admin/alumni'
    | '/admin/committee'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/members'
    | '/admin/notices'
    | '/admin/upazila-info'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alumni'
    | '/auth'
    | '/committee'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/members'
    | '/notices'
    | '/teachers'
    | '/upazilas'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/upazila/$slug'
    | '/_authenticated/admin/alumni'
    | '/_authenticated/admin/committee'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/upazila-info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlumniRoute: typeof AlumniRoute
  AuthRoute: typeof AuthRoute
  CommitteeRoute: typeof CommitteeRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  NoticesRoute: typeof NoticesRoute
  TeachersRoute: typeof TeachersRoute
  UpazilasRoute: typeof UpazilasRoute
  UpazilaSlugRoute: typeof UpazilaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upazilas': {
      id: '/upazilas'
      path: '/upazilas'
      fullPath: '/upazilas'
      preLoaderRoute: typeof UpazilasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upazila/$slug': {
      id: '/upazila/$slug'
      path: '/upazila/$slug'
      fullPath: '/upazila/$slug'
      preLoaderRoute: typeof UpazilaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/upazila-info': {
      id: '/_authenticated/admin/upazila-info'
      path: '/admin/upazila-info'
      fullPath: '/admin/upazila-info'
      preLoaderRoute: typeof AuthenticatedAdminUpazilaInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/admin/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/committee': {
      id: '/_authenticated/admin/committee'
      path: '/admin/committee'
      fullPath: '/admin/committee'
      preLoaderRoute: typeof AuthenticatedAdminCommitteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/alumni': {
      id: '/_authenticated/admin/alumni'
      path: '/admin/alumni'
      fullPath: '/admin/alumni'
      preLoaderRoute: typeof AuthenticatedAdminAlumniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAlumniRoute: typeof AuthenticatedAdminAlumniRoute
  AuthenticatedAdminCommitteeRoute: typeof AuthenticatedAdminCommitteeRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminUpazilaInfoRoute: typeof AuthenticatedAdminUpazilaInfoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAlumniRoute: AuthenticatedAdminAlumniRoute,
  AuthenticatedAdminCommitteeRoute: AuthenticatedAdminCommitteeRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminUpazilaInfoRoute: AuthenticatedAdminUpazilaInfoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlumniRoute: AlumniRoute,
  AuthRoute: AuthRoute,
  CommitteeRoute: CommitteeRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  NoticesRoute: NoticesRoute,
  TeachersRoute: TeachersRoute,
  UpazilasRoute: UpazilasRoute,
  UpazilaSlugRoute: UpazilaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
